### PR TITLE
Fix tests for windows, which appears to have a lower resolution time

### PR DESCRIPTION
**Pull request by sfider**
Tests have around 19 fails when run on windows. Mostly ```OSError: [Errno 22] Invalid argument``` on ```4000``` timestamps (too low resolution time).

```test_push``` also had issues with recorded times comparing as equal (again, low resolution time). But I also noticed it used ```arrow.now()``` while tested code uses ```arrow.utcnow()```, so I fixed this as well.

### CODE REVIEW

**Review by teutat3s — COMMENTED** [review]
Thank you for fixing this. Could you fix the linting issues? Then this would look good to go from my side.

**Comment by sfider** [comment]
> Thank you for fixing this. Could you fix the linting issues? Then this would look good to go from my side.

Sorry, I was going to, but I'm really swamped with work. I would have to figure out how to run lint test locally not to push something that would fail again XD

**Comment by teutat3s** [comment]
No worries and no rush. This is the command we run in the CI:

```
flake8 --show-source watson/ tests/ scripts/
```

**Review by b12f — APPROVED** [review]

**Comment by b12f** [comment]
Thanks @sfider!

**Pull request merged**
